apiVersion: apps/v1

# 자원의 종류(Pod, Service, ReplicaSet, Deployment)
kind: Deployment

metadata:
  name: product-deployment
  namespace: lgcns

spec:
  # 자원 공간의 낭비를 방지하고 관리의 편의성을 제공해주는 옵션!!!
  revisionHistoryLimit: 2
  
  replicas: 1
  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product
    spec:
      # docker container 
      containers:
        - name: product-container
          # ecr 경로
          image: 933090817123.dkr.ecr.ap-northeast-2.amazonaws.com/product-service:latest
          ports:
          - containerPort: 8080
          resources:
            # 컨테이너가 사용할 수 있는 최대치의 리소스
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
          # sevret 작성 후 외부환경변수를 이용해서 파드 실행시 주입할 예정
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_HOST
                
          - name: DB_ADMIN
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_ADMIN

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_PASSWORD
            # 컨테이너 상태 확인
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080


---
# core service setting
# core group : pod, service, ConfigMap, Secret, namespace
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: lgcns
spec:
# 클러스터 내부에서 접근할 수 있는 IP 타입
  type: ClusterIP 
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: product